version: '0.1'
services:
  backend: 
    build: .
    ports:
      - 8000:9000
    volumes:
      - .:/app
    depends_on:
       - db  
  db:
      image: mysql:8.0.30
      restart: always
      environment:
          MYSQL_DATABASE: social
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
      volumes:
        - .dbdata:/var/lib/mysql    
      ports:
        - :33006:3306  
